### ISSUE TITLE
GPL license

### ISSUE THREAD

**Issue by Alex-Vaduva** [dosfstools/dosfstools#51]
Hello,

I saw that dosfstools is based on mkdosfs and dosfsck. Mkdosfs in licensed under GPL-2.0 or any later version but from my research, dosfsck is licensed under GPL-2.0 only. Can you please give me more details as GPL-2.0 is incompatible with GPL-3.0? Did the author give you permission to upgrade it to GPL-3.0?

Thank you.

**Comment by pali** [comment]
Seems it is not a problem as mkdosfs and dosfsck are two separate tools in two separate binaries and each distributed under its license. GPL does not forbid to distribute one binary under GPLv2 and one under GPLv3.

**Comment by Alex-Vaduva** [comment]
I beg to differ, as GPL-2.0 obligates you to give the whole software under GPL-2.0. That is why version 2 is incompatible with version 3. You can make a research regarding this issue

**Comment by pali** [comment]
That is not truth. If you take Linux distribution like Debian or Ubuntu, it contains couple of GPLv2-only, GPLv3-only and BSD-only programs and still Debian or Ubuntu software is distributed.

Problem is only if one binary would contain both GPLv2-only and GPLv3-only code.

You can even call proprietary binaries from GPLv2-only binaries and it is not licence violation.

**Comment by andreasbombe** [comment]
Ok, first I did not upgrade it to GPL v3, that happened before I adopted the project, so I can not tell you what work went into it. I noticed this discrepancy only later.

That said, I don't think there really was GPL v2 only code in there. The v2-only license appears to be what is found in the Linux kernel, but I doubt there has been a transfer of code relevant for copyright claims. Same with the copyright by Linus Torvalds, I don't think he ever actively contributed to these programs.

My impression is that in the past some kernel include files as installed were included in some source files, some data structure and bit definitions were copied and possibly a few lines of code. And that was the reason the license and Torvalds copyright was included even though that is rather overzealous regarding for a few structs and defines.

If have done your own research and found something more definite, please elaborate.

**Comment by pali** [comment]
I have looked into history and have not find any info that dosfsck is licensed under GPLv2-only. So @Alex-Vaduva where is this written?

Also even if one tool is licensed under GPLv2-only and another under GPLv3-only there is no license violation. You are not obligated to distribute whole software under one license as @Alex-Vaduva. See e.g. Debian software -- it contains lot of GPLv2-only programs and also more GPLv3+ programs. Similarly dosfstools can distribute one program under GPLv2-only and another under GPLv3+. What you are not allowed is to mix GPLv2-only source code into GPLv3+ and build from it one executable program (or library). Or you cannot link GPLv2-only program into GPLv3+. But build two separate programs, one under GPLv2-only and one under GPLv3+ and distribute them is perfectly fine.

@andreasbombe Because nobody provided more information for more then year, I suggest to close this as invalid.
