### ISSUE TITLE
dosfsck man page file is missing from dosfstools-4.1.tar.xz

### ISSUE THREAD

**Issue by OSS542** [dosfstools/dosfstools#60]
Only occurs if "--enable-compat-symlinks" configure switch is not used.

**Comment by andreasbombe** [comment]
I'm unclear on what you mean by missing from that archive. Do you mean there is no *dosfsck(1)* man page installed? Because it's called *fsck.fat(1)* and the compatibility symlink from the old name is only created with the configure option you mentioned.

If you meant that there is some problem with `make dist` I don't see anything wrong.

**Comment by OSS542** [comment]
As I recall, I somehow managed to end up with a link but no file, or so I seem to remember.
I have just tried to recreate the problem I ran into, but have not been able to do that.
It therefore seems to be an error on my part (brain malfunction).  I suggest we close this as invalid ("works for me").
